ERROR - 2025-04-26 16:48:57 --> Exception: no such table: panier in C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php(175): SQLite3->exec('DELETE FROM `pa...')
#1 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('DELETE FROM `pa...')
#2 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pa...')
#3 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseBuilder.php(2773): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pa...', NULL, false)
#4 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(928): CodeIgniter\Database\BaseBuilder->truncate()
#5 C:\xampp\htdocs\Atelier 1 DevOps\tests\Models\PanierModelTest.php(19): CodeIgniter\Model->__call('truncate', Array)
#6 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(2437): App\Tests\Models\PanierModelTest->setUp()
#7 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(2340): PHPUnit\Framework\TestCase->invokeHookMethods(Object(PHPUnit\Runner\HookMethodCollection), Object(PHPUnit\Event\DispatchingEmitter), 'beforeTestMetho...', 'beforeTestMetho...', 'beforeTestMetho...')
#8 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(506): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#9 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\PanierModelTest))
#11 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp\htdocs\Atelier 1 DevOps\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2025-04-26 16:48:57 --> Exception: no such table: panier in C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php(175): SQLite3->exec('DELETE FROM `pa...')
#1 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('DELETE FROM `pa...')
#2 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pa...')
#3 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseBuilder.php(2773): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pa...', NULL, false)
#4 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(928): CodeIgniter\Database\BaseBuilder->truncate()
#5 C:\xampp\htdocs\Atelier 1 DevOps\tests\Models\PanierModelTest.php(19): CodeIgniter\Model->__call('truncate', Array)
#6 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(2437): App\Tests\Models\PanierModelTest->setUp()
#7 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(2340): PHPUnit\Framework\TestCase->invokeHookMethods(Object(PHPUnit\Runner\HookMethodCollection), Object(PHPUnit\Event\DispatchingEmitter), 'beforeTestMetho...', 'beforeTestMetho...', 'beforeTestMetho...')
#8 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(506): PHPUnit\Framework\TestCase->invokeBeforeTestHookMethods(Array, Object(PHPUnit\Event\DispatchingEmitter))
#9 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\PanierModelTest))
#11 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp\htdocs\Atelier 1 DevOps\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2025-04-26 18:49:47 --> Exception: Unable to prepare statement: 1, no such table: users in C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php:176
Stack trace:
#0 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php(176): SQLite3->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Atelier 1 DevOps\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Atelier 1 DevOps\tests\Models\UserModelTest.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp\htdocs\Atelier 1 DevOps\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2025-04-26 18:49:47 --> Exception: no such table: users in C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\SQLite3\Connection.php(175): SQLite3->exec('INSERT INTO `us...')
#1 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Atelier 1 DevOps\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Atelier 1 DevOps\tests\Models\UserModelTest.php(17): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\xampp\htdocs\Atelier 1 DevOps\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#17 {main}
ERROR - 2025-04-26 20:40:28 --> mysqli_sql_exception: Table 'devops_db.users' doesn't exist in C:\xampp\htdocs\Atelier 1 DevOps\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Atelier 1 DevOps\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Atelier 1 DevOps\tests\Models\UserModelTest.php(10): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp\htdocs\Atelier 1 DevOps\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2025-04-26 20:40:31 --> mysqli_sql_exception: Table 'devops_db.users' doesn't exist in C:\xampp\htdocs\Atelier 1 DevOps\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\Atelier 1 DevOps\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Atelier 1 DevOps\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Atelier 1 DevOps\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Atelier 1 DevOps\tests\Models\UserModelTest.php(17): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\xampp\htdocs\Atelier 1 DevOps\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\xampp\htdocs\Atelier 1 DevOps\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#17 {main}
